_base_: '../_base_/kitti_mono.yml'

batch_size: 8
iters: 70000

train_dataset:
  transforms:
    - type: LoadImage
      reader: pillow
      to_chw: False
    - type: Gt2SmokeTarget
      mode: train
      num_classes: 3
      input_size: [1280, 384]
    - type: Normalize
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]

val_dataset:
  transforms:
    - type: LoadImage
      reader: pillow
      to_chw: False
    - type: Gt2SmokeTarget
      mode: val
      num_classes: 3
      input_size: [1280, 384]
    - type: Normalize
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]

optimizer:
  type: Adam

lr_scheduler:
  type: MultiStepDecay
  milestones: [36000, 55000]
  learning_rate: 1.25e-4

model:
  type: SMOKE
  backbone:
    type: DLA34
    # This will automatically save to ~/.paddle3d/pretrained/dla34/dla34.pdparams
    pretrained: "https://bj.bcebos.com/paddle3d/pretrained/dla34.pdparams"
  head:
    type: SMOKEPredictor
    num_classes: 3
    reg_channels: [1, 2, 3, 2, 2]
    num_channels: 256
    norm_type: "gn"
    in_channels: 64
  depth_ref: [28.01, 16.32]
  # dim_ref is the reference size mentioned in the paper, the order here is [l, h, w]
  dim_ref: [[3.88, 1.63, 1.53], [1.78, 1.70, 0.58], [0.88, 1.73, 0.67]]
  max_detection: 50
  pred_2d: True

export:
  transforms:
    - type: LoadImage
      reader: pillow
      to_chw: False
      to_rgb: True
    - type: Normalize
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]
